version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    env_file:
      - ./env/local.env
      - ./env/.env
    depends_on:
      - database
    networks:
      - nestjs_network
    ports:
      - 3000:3000

  database:
    image: postgres:9.6-alpine
    ports:
      - nestjs_api:5432
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - nestjs_network

volumes:
  database-data: {}

networks:
  nestjs_network:
    driver: bridge
