version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ecommerce-market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lucas66R99

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ecommerce-market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lucas66R99
      REDIS_HOST: redis
      REDIS_PORT: 6379
