version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    env_file:
      - ./env/local.env
      - ./env/.env
    depends_on:
      - database
    networks:
      - nestjs_network
    ports:
      - 3000:3000

  database:
    image: postgres:9.6-alpine
    ports:
      - 11543:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - nestjs_network

volumes:
  database-data: {}

networks:
  nestjs_network:
    driver: bridge
